# Generated by Django 5.0.6 on 2024-07-02 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0005_rename_usuario_producto_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='codigo',
            field=models.CharField(default=12345, max_length=1000),
            preserve_default=False,
        ),
    ]
