# Generated by Django 5.0.6 on 2024-07-26 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0007_alter_producto_codigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='precio_compra',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
